#!/usr/bin/env bash

bp_prompt_value() { local prompt="$1" default="$2" validator="$3" value; while true; do printf '%s [%s]: ' "$prompt" "$default"; IFS= read -r value || bp_die "Input ended unexpectedly."; value="${value:-$default}"; if "$validator" "$value"; then ANSWER="$value"; return; fi; printf 'Invalid value. Please try again.\n' >&2; done; }
bp_answer_or_prompt_value() { local key="$1" prompt="$2" default="$3" validator="$4" value; if "$ANSWERS_MODE"; then value="${ANSWERS[$key]}"; "$validator" "$value" || bp_die "Invalid answer value: $key"; ANSWER="$value"; else bp_prompt_value "$prompt" "$default" "$validator"; fi; }
bp_prompt_yes_no() { local prompt="$1" default="$2" value; while true; do printf '%s [%s]: ' "$prompt" "$default"; IFS= read -r value || bp_die "Input ended unexpectedly."; value="${value:-$default}"; case "$value" in y|Y) ANSWER=y; return ;; n|N) ANSWER=n; return ;; *) printf 'Invalid value. Enter y or n.\n' >&2 ;; esac; done; }
bp_answer_or_prompt_yes_no() { local key="$1" prompt="$2" default="$3" value; if "$ANSWERS_MODE"; then value="${ANSWERS[$key]}"; [[ "$value" == y || "$value" == n ]] || bp_die "Invalid answer value: $key"; ANSWER="$value"; else bp_prompt_yes_no "$prompt" "$default"; fi; }
bp_prompt_port() { local value; while true; do printf 'Fixed host DB port for HeidiSQL/DBeaver [empty = automatic]: '; IFS= read -r value || bp_die "Input ended unexpectedly."; if [[ -z "$value" ]] || bp_valid_port "$value"; then ANSWER="$value"; return; fi; printf 'Invalid port. Enter 1-65535 or leave it empty.\n' >&2; done; }
bp_prompt_hostnames() { local value; while true; do printf 'Hostnames/FQDNs separated by commas [empty = none]: '; IFS= read -r value || bp_die "Input ended unexpectedly."; bp_set_hostnames "$value" && return; printf 'Invalid hostname/FQDN. Please try again.\n' >&2; done; }
bp_prompt_extensions() { local value default_list; default_list="$(IFS=,; printf '%s' "${DEFAULT_OPTIONAL_EXTENSIONS[*]}")"; while true; do printf 'PHP extensions [intl,gd]: '; IFS= read -r value || bp_die "Input ended unexpectedly."; [[ -z "$value" ]] && value="$default_list"; bp_set_extensions "$value" && return; done; }
